---
- hosts: localhost
  become: true
  vars: 
    - ansible_shell_allow_world_readable_temp: true
  pre_tasks:
    - name: update repositories (CentOS/Rocky)
      dnf:
       update_cache=yes
      when: ansible_distribution == "CentOS" or "ansible_distribution" == "Rocky" or "ansible_distribution" == "RedHat"

    - name: update repositories (Debian/Ubuntu)
      apt:
       update_cache=yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
    - include: tasks/gnome.yml
