---
- hosts: localhost
  tags: always
  become: true
  vars: 
    - ansible_shell_allow_world_readable_temp: true
    - docker_repo_key_url: https://download.docker.com/linux/ubuntu/gpg
    - hashicorp_repo_key_url: https://apt.releases.hashicorp.com/gpg
    - syncthing_repo_key_url: https://syncthing.net/release-key.gpg
    - zerotier_repo_key_url: http://download.zerotier.com/contact%40zerotier.com.gpg
  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (CentOS/Rocky/RHEL)
      tags: always
      dnf: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["CentOS", "Rocky", "RedHat"]

    - name: pre-run | update package cache (Debian/Ubuntu)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

  tasks:
    - name: Setup users
      ansible.builtin.import_tasks: tasks/users.yml
    - name: Setup cron
      ansible.builtin.import_tasks: tasks/cron.yml
    - name: Setup package
      ansible.builtin.import_tasks: tasks/packages.yml
    - name: Setup apt keys
      ansible.builtin.import_tasks: tasks/aptkey.yml
    - name: Setup gnome
      ansible.builtin.import_tasks: tasks/gnome.yml
