- name: "Install packages (CentOS/Rocky/RHEL)"
  dnf:
    name:
      - htop
      - mc
      - tmux
      - vim
      - nfs-utils
    state: present
  when: ansible_facts['os_family'] == "CentOS" or ansible_facts['os_family'] == "Rocky" or ansible_facts['os_family'] == "RedHat"

- name: "Install packages (Debian/Ubuntu)"
  apt:
    name:
      - htop
      - mc
      - tmux
      - vim
      - nfs-common
    state: present
  when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Ubuntu'
