- name: "Install packages (CentOS/Rocky/RHEL)"
  dnf:
    name:
      - htop
      - mc
      - tmux
      - vim
    state: present
  when: ansible_distribution == "CentOS" or "ansible_distribution" == "Rocky" or "ansible_distribution" == "RedHat"

- name: "Install packages (Debian/Ubuntu)"
  apt:
    name:
      - htop
      - mc
      - tmux
      - vim
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
