- name: add john group
  ansible.builtin.group:
    name: john
    state: present
    gid: 501
    
- name: add john user
  user: name=john system=no state=present uid=501 shell=/bin/bash createhome=yes home=/home/john

- name: set john home directory ownership
  ansible.builtin.file:
    path: /home/john
    state: directory
    owner: john
    group: john

- name: set up sudo for john
  copy: src=files/sudoer_john dest=/etc/sudoers.d/john owner=root group=root mode=0440

- name: copy custom .bashrc file
  copy: src=files/bashrc dest=/home/john/.bashrc owner=john group=john

- name: add ansible group
  ansible.builtin.group:
    name: velociraptor
    state: present
    gid: 9999

- name: add ansible user
  user: name=velociraptor system=no state=present uid=9999 groups=velociraptor shell=/bin/bash createhome=yes home=/home/velociraptor
  
- name: set ansible home directory permissions
  ansible.builtin.file:
    path: /home/velociraptor
    state: directory
    owner: velociraptor
    group: velociraptor
    recurse: yes
    
- name: set up sudo for ansible
  copy: src=files/sudoer_velociraptor dest=/etc/sudoers.d/velociraptor owner=root group=root mode=0440
